### ISSUE TITLE
Building guzuta fails

### ISSUE THREAD

**Issue by DrRac27** [eagletmt/guzuta#10]
I maintain the AUR package for guzuta and it didn't build anymore successfully. I was able to fix it by updating gpgme.
- I got this error: https://github.com/gpg-rs/libgpg-error/issues/7
- My "fix" for it: https://aur.archlinux.org/cgit/aur.git/commit/?h=guzuta-git&id=4cdb6769b9df0af715c45a169199d0ca1fb60bb9

**Comment by eagletmt** [comment]
I've released v0.5.0 which contains the gpgme fix.
https://crates.io/crates/guzuta/0.5.0
https://github.com/eagletmt/guzuta/releases/tag/v0.5.0

**Comment by DrRac27** [comment]
Thanks, updated the AUR package.
